---
title: "Health Predictions"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
css: styles.css
---

```{r setup, include=FALSE}

### To change to new data set, replace penguins everywhere :) 
library(flexdashboard)
library(palmerpenguins)
library(caret) 
library(DT)
library(ggplot2)
library(sortable)
library(modelr)
health_data = read.csv("updated_data.csv", header = TRUE ,sep = ",")
exists("health_data")
```


Build model
=====================================  
  


Column {data-width=300}
----------------------------------------------------------------------- 

```{r}
  bucket_list(
        header = "Drag variables to build your model",
        group_name = "bucket_list_group",
        orientation = "vertical",
        add_rank_list(
          text = "Not used",
          # change the variable names
          labels = names(health_data),
          input_id = "out_model"
        ),
        add_rank_list(
          text = "Used",
          labels = NULL,
          input_id = "in_model"
        )
      )
```



Column {data-width=400}
-----------------------------------------------------------------------

### Predictions vs truth

```{r}

model1 <- reactive({
  if(length(input$in_model) > 0){
    #change this to new data
    lm1 = lm(as.formula(paste0("trig_mean-normal_tm1 ~ ",paste0(input$in_model,collapse="+"))),
         data=health_data)
  }else{
    # change to new data
    lm1 = lm(trig_mean-normal_tm1 ~ 1,data=health_data)
  }
  
})

```

```{r}
renderPlot({ 
  
   # changed to new data
health_data %>%
    add_predictions(model1()) %>%
    ggplot(aes_string(x="trig_mean-normal_tm1",y="pred")) +
    geom_point()

})
```

### RMSE

```{r}
renderText({
  sqrt(sum(model1()$residuals^2))
})
```



Health Data
===================================== 


```{r}
   # changed to new data
datatable(health_data,fillContainer = FALSE) 
```


Explore Health Data
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------



```{r}
   # changed to new data
radioButtons("plottype", h4("Plot type"),
                        choices = c("scatterplot","boxplot"),selected="scatterplot")

selectInput("xvariable", h4("Pick x-variable"),
                        choices = colnames(health_data), selected="trig_mean-normal_tm1")

selectInput("yvariable", h4("Pick y-variable"),
                        choices = colnames(health_data), selected="gagne_sum_t")

```

Column 
-----------------------------------------------------------------------

### Health plot

```{r}

# change to new data
renderPlot(
  if(input$plottype=="scatterplot"){
    health_data %>% 
      ggplot(aes_string(x=input$xvariable,y=input$yvariable)) + geom_point()
  }else{
    health_data %>% 
      ggplot(aes_string(x=input$xvariable,y=input$yvariable)) + geom_boxplot()
  }
)
```



